# For easy reading purpose, I changed the format a bit

In [2]:
import numpy as np
import pandas as pd

## 1. Numpy Arrays:  14 points

**1) create 1 array of 10 zeros, 1 array of 10 fives. - 2 points**

In [3]:
zero_array=np.zeros(10)
one_array=np.ones(10)

In [4]:
zero_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
one_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**2) create a 3x3x3 array filled with arbitrary values. - 2 points**

In [12]:
np.random.seed(42)
np.random.randn(3,3,3)

array([[[ 0.49671415, -0.1382643 ,  0.64768854],
        [ 1.52302986, -0.23415337, -0.23413696],
        [ 1.57921282,  0.76743473, -0.46947439]],

       [[ 0.54256004, -0.46341769, -0.46572975],
        [ 0.24196227, -1.91328024, -1.72491783],
        [-0.56228753, -1.01283112,  0.31424733]],

       [[-0.90802408, -1.4123037 ,  1.46564877],
        [-0.2257763 ,  0.0675282 , -1.42474819],
        [-0.54438272,  0.11092259, -1.15099358]]])

**3) create an array with the values 1, 7, 13, 105, 208 and determine the size of the memory occupied by the array. - 2 ponits**

In [25]:
array_=np.array([1,7,13,205,208])
print("size: ",array_.size)
print("Memory: %d bytes" % (array_.size * array_.itemsize))

size:  5
Memory: 20 bytes


**4) create a 3x4 matrix filled with values from 10 to 21. - 2 ponits**

In [20]:
mat=np.arange(10,22).reshape(3,4)
mat

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

**5) create an 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal. 4 points**

In [36]:
mat=np.zeros((4,4))

#stagger values for rows 1, 3
mat[::2,1::2]=1

#stagger values for rows 2, 4
mat[1::2,::2]=1

mat

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

**6) Append values to the end of an array: 2 points**

Original array: [10, 20, 30]; append two arrays to it: [40, 50, 60], [70, 80, 90]

Expected output:
Original array: [10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]**

In [40]:
a1=np.array([10,20,30])
a2=np.array([40,50,60])
a3=np.array([70,80,90])

np.concatenate((a1,a2,a3),axis=0)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])


**2. Create a random array with 1000 elements and compute the average, variance, standard deviation of the array elements. 3 points**


In [42]:
r=np.random.rand(1000)
r

array([0.23000884, 0.12056689, 0.0769532 , 0.69628878, 0.33987496,
       0.72476677, 0.06535634, 0.31529034, 0.53949129, 0.79072316,
       0.3187525 , 0.62589138, 0.88597775, 0.61586319, 0.23295947,
       0.02440078, 0.87009887, 0.02126941, 0.87470167, 0.52893713,
       0.9390677 , 0.79878324, 0.99793411, 0.35071182, 0.76718829,
       0.40193091, 0.47987562, 0.62750546, 0.87367711, 0.98408347,
       0.76827341, 0.41776678, 0.421357  , 0.7375823 , 0.23877715,
       0.11047411, 0.35462216, 0.28723899, 0.29630812, 0.23360775,
       0.04209319, 0.01787393, 0.98772239, 0.42777313, 0.38432665,
       0.67964728, 0.21825389, 0.94996118, 0.78634501, 0.089411  ,
       0.41758078, 0.87911831, 0.94473202, 0.46740151, 0.61341139,
       0.16703395, 0.99116863, 0.2316717 , 0.94273177, 0.64964665,
       0.60773679, 0.51268851, 0.23066981, 0.17652803, 0.22048621,
       0.18643826, 0.77958447, 0.35012526, 0.05784268, 0.96910263,
       0.88378588, 0.92775228, 0.99490782, 0.17389525, 0.39624

In [50]:
print("Mean: ",np.mean(r))
print("Standard Deviation: ",np.std(r))
print("Variance: ",np.var(r))

Mean:  0.5026927803498391
Standard Deviation:  0.29151809219351826
Variance:  0.08498279807614861



**3. Compute the trigonometric sine, cosine and tangent array of angles given in degrees. 3 points
   Sample degree: 0, 30, 45, 60, 90**
   
Expected Output:<br>
sine: array of angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]<br><br>
cosine: array of angles given in degrees<br>
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01 6.12323400e-17]<br><br>
tangent: array of angles given in degrees<br>
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00 1.63312394e+16]

In [57]:
sin_array=np.array([0.         ,0.5      ,  0.70710678, 0.8660254,  1.  ])
print("Sine: ",np.sin(sin_array))
print("\n")
cos_array=np.array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01 ,5.00000000e-01, 6.12323400e-17 ])
print("Cosine: ",np.cos(cos_array))
print("\n")
tan_array=np.array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00, 1.63312394e+16  ])
print("Tangent: ",np.tan(tan_array))

Sine:  [0.         0.47942554 0.64963694 0.76175998 0.84147098]


Cosine:  [0.54030231 0.64785934 0.7602446  0.87758256 1.        ]


Tangent:  [ 0.          0.65138789  1.55740772 -6.14753307 -0.48456903]


## 4. Array Slicing: 5 questions, 20 points,4 points each
**Given an array:
array([ 3,  6,  9,  25, 10,  8])**

In [54]:
a=np.array([ 3,  6,  9,  25, 10,  8])
a

array([ 3,  6,  9, 25, 10,  8])

**1) To get all elements except the first:**

In [61]:
a[1:]

array([ 6,  9, 25, 10,  8])

**2) To get all elements except the last:**

In [60]:
a[:-1]

array([ 3,  6,  9, 25, 10])

**3) To get every other element of the array (operation from the first element):**

In [65]:
a[0::2]

array([ 3,  9, 10])

**4) To get every element of the array (operation from the second element):**

In [71]:
a[1::2]

array([ 6, 25,  8])

**5) To reverse the array:**

In [70]:
a[-1::-1]

array([ 8, 10, 25,  9,  6,  3])


## 5. Multidimensional Arrays: 4 questions, 20 points, 5 points each


**1) create an array with the components as 0-31 and the shape is (8,4)**

In [74]:
a=np.arange(0,32).reshape(8,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

**2) set the 3rd element in the 1st row to 0**


In [75]:
a[0,2]=0
a

array([[ 0,  1,  0,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

**3) print the second column**


In [80]:
print(a[:,1])

[ 1  5  9 13 17 21 25 29]


**4) select any 3x3 region from the array**

In [81]:
a[:3,:3]

array([[ 0,  1,  0],
       [ 4,  5,  6],
       [ 8,  9, 10]])

## 6. Broadcasting: 40 points

**1. Please add the following two arrays. You can reshape the array by np.reshape or 'newaxis'. (20 points)**

**1) Solutions:**

In [86]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])

In [88]:
b[:,np.newaxis]+a

array([[ 1., 11., 21., 31.],
       [ 2., 12., 22., 32.],
       [ 3., 13., 23., 33.]])

**2) Solutions:**

In [89]:
x = np.arange(4)
y = np.ones(5)

In [92]:
x[:,np.newaxis]+y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

### 2. Write a 6x6 times table matrix 
 

**by using numpy broadcasting (10 points)**


In [124]:
a = np.zeros(6).reshape((6, 1))
b = np.ones(6)

mat=a+b
mat

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

**by using Python nested for-loop (10 points).**

In [123]:
nrow=6
ncol=6
mat = []

for j in range(ncol):
    row = []
    for i in range(nrow):
        row.append(1.0)
       
    mat.append(row)
np.array(mat)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])